import type { InvoiceTemplate } from '@invoice-generator/shared-types'

/**
 * System Templates - Available to ALL users
 *
 * These templates are:
 * - Static (defined in code, not localStorage)
 * - Protected (cannot be deleted or modified)
 * - Distinguished by isSystem: true
 *
 * Design principles (Vercel-inspired):
 * - Monochrome palette (black/white/gray)
 * - Clean typography hierarchy
 * - Minimal borders, subtle dividers
 * - Grid-aligned elements
 * - Professional, modern enterprise feel
 *
 * Positioning Notes:
 * - A4 page: 595.28 x 841.89 pts
 * - With 50pt margins on all sides, content area: 495pt x 741pt
 * - Full content width: 495pt
 * - All elements positioned within 0-495pt width range
 * - Right-aligned elements: x + width <= 495
 */

// System template IDs (prefixed to avoid collision with user templates)
export const SYSTEM_TEMPLATE_IDS = {
  VERCEL_MINIMAL: 'system-vercel-minimal',
  VERCEL_PROFESSIONAL: 'system-vercel-professional',
  VERCEL_EXECUTIVE: 'system-vercel-executive',
  VERCEL_MODERN: 'system-vercel-modern',
  VERCEL_CLASSIC: 'system-vercel-classic',
} as const

// The default system template ID
export const DEFAULT_SYSTEM_TEMPLATE_ID = SYSTEM_TEMPLATE_IDS.VERCEL_MINIMAL

/**
 * Template 1: Vercel Minimal
 *
 * - Pure white background (#ffffff)
 * - Black text (#000000), gray secondary (#666666)
 * - Large "INVOICE" title (24pt, uppercase)
 * - Clean two-column header layout
 * - Minimal table styling with subtle borders (#e5e5e5)
 */
const vercelMinimalTemplate: InvoiceTemplate = {
  id: SYSTEM_TEMPLATE_IDS.VERCEL_MINIMAL,
  name: 'Vercel Minimal',
  description: 'Clean, modern invoice design with generous whitespace and minimal styling',
  pageSize: 'A4',
  orientation: 'portrait',
  margins: {
    top: 50,
    right: 50,
    bottom: 50,
    left: 50,
  },
  theme: {
    primary: '#000000',
    secondary: '#666666',
    accent: '#000000',
    text: '#000000',
    textLight: '#666666',
    background: '#ffffff',
  },
  backgroundColor: '#ffffff',
  isDefault: true,
  isSystem: true,
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  elements: [
    // INVOICE Title (large, uppercase)
    {
      id: 'sys-minimal-title',
      type: 'text',
      name: 'Invoice Title',
      position: { x: 0, y: 0, width: 160, height: 32 },
      content: 'INVOICE',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 24,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'uppercase',
        letterSpacing: 2,
        lineHeight: 1.2,
        color: '#000000',
      },
      padding: 0,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
    },
    // Invoice Number
    {
      id: 'sys-minimal-invoice-number',
      type: 'text',
      name: 'Invoice Number',
      position: { x: 0, y: 36, width: 160, height: 16 },
      content: '#{{invoice_number}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 10,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.4,
        color: '#666666',
      },
      padding: 0,
      opacity: 1,
      zIndex: 1,
      locked: false,
      visible: true,
    },
    // From Block (right side)
    {
      id: 'sys-minimal-from',
      type: 'text',
      name: 'From',
      position: { x: 315, y: 0, width: 180, height: 60 },
      content: '{{from_name}}\n{{from_address}}\n{{from_city}}, {{from_state}} {{from_postal_code}}\n{{from_email}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'right',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.4,
        color: '#000000',
      },
      padding: 0,
      opacity: 1,
      zIndex: 2,
      locked: false,
      visible: true,
    },
    // Divider Line - full width
    {
      id: 'sys-minimal-divider-1',
      type: 'divider',
      name: 'Header Divider',
      position: { x: 0, y: 70, width: 495, height: 1 },
      content: '',
      backgroundColor: '#e5e5e5',
      padding: 0,
      opacity: 1,
      zIndex: 3,
      locked: false,
      visible: true,
    },
    // Bill To Label
    {
      id: 'sys-minimal-bill-to-label',
      type: 'text',
      name: 'Bill To Label',
      position: { x: 0, y: 85, width: 60, height: 12 },
      content: 'BILL TO',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 8,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'uppercase',
        letterSpacing: 1,
        lineHeight: 1.2,
        color: '#666666',
      },
      padding: 0,
      opacity: 1,
      zIndex: 4,
      locked: false,
      visible: true,
    },
    // Bill To Block
    {
      id: 'sys-minimal-bill-to',
      type: 'text',
      name: 'Bill To',
      position: { x: 0, y: 100, width: 180, height: 55 },
      content: '{{to_name}}\n{{to_address}}\n{{to_city}}, {{to_state}} {{to_postal_code}}\n{{to_email}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.4,
        color: '#000000',
      },
      padding: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
    },
    // Dates Block (right side)
    {
      id: 'sys-minimal-dates',
      type: 'text',
      name: 'Dates',
      position: { x: 315, y: 85, width: 180, height: 60 },
      content: 'Issue Date: {{issue_date}}\nDue Date: {{due_date}}\nPeriod: {{billing_period}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'right',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.6,
        color: '#000000',
      },
      padding: 0,
      opacity: 1,
      zIndex: 6,
      locked: false,
      visible: true,
    },
    // Work Hours Table - full width
    {
      id: 'sys-minimal-work-hours',
      type: 'table_work_hours',
      name: 'Work Hours',
      position: { x: 0, y: 165, width: 495, height: 140 },
      content: '',
      tableStyle: {
        headerBackgroundColor: '#fafafa',
        headerTextColor: '#000000',
        rowBackgroundColor: '#ffffff',
        alternateRowBackgroundColor: '#ffffff',
        borderColor: '#e5e5e5',
        showHeaderBorder: true,
        showRowBorders: true,
      },
      padding: 0,
      opacity: 1,
      zIndex: 7,
      locked: false,
      visible: true,
    },
    // Line Items Table - full width
    {
      id: 'sys-minimal-line-items',
      type: 'table_line_items',
      name: 'Line Items',
      position: { x: 0, y: 315, width: 495, height: 90 },
      content: '',
      tableStyle: {
        headerBackgroundColor: '#fafafa',
        headerTextColor: '#000000',
        rowBackgroundColor: '#ffffff',
        alternateRowBackgroundColor: '#ffffff',
        borderColor: '#e5e5e5',
        showHeaderBorder: true,
        showRowBorders: true,
      },
      padding: 0,
      opacity: 1,
      zIndex: 8,
      locked: false,
      visible: true,
    },
    // Summary Table
    {
      id: 'sys-minimal-summary',
      type: 'table_summary',
      name: 'Summary',
      position: { x: 305, y: 420, width: 190, height: 85 },
      content: '',
      tableStyle: {
        headerBackgroundColor: '#000000',
        headerTextColor: '#ffffff',
        rowBackgroundColor: '#ffffff',
        alternateRowBackgroundColor: '#fafafa',
        borderColor: '#e5e5e5',
        showHeaderBorder: false,
        showRowBorders: true,
      },
      padding: 0,
      opacity: 1,
      zIndex: 9,
      locked: false,
      visible: true,
    },
    // Notes Section
    {
      id: 'sys-minimal-notes-label',
      type: 'text',
      name: 'Notes Label',
      position: { x: 0, y: 520, width: 50, height: 12 },
      content: 'NOTES',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 8,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'uppercase',
        letterSpacing: 1,
        lineHeight: 1.2,
        color: '#666666',
      },
      padding: 0,
      opacity: 1,
      zIndex: 10,
      locked: false,
      visible: true,
    },
    {
      id: 'sys-minimal-notes',
      type: 'text',
      name: 'Notes',
      position: { x: 0, y: 535, width: 220, height: 40 },
      content: '{{notes}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.4,
        color: '#666666',
      },
      padding: 0,
      opacity: 1,
      zIndex: 11,
      locked: false,
      visible: true,
    },
  ],
}

/**
 * Template 2: Vercel Professional
 *
 * - White background with subtle gray accent blocks (#fafafa)
 * - Black header bar for branding
 * - More structured layout with labeled sections
 * - Formal/corporate aesthetic
 */
const vercelProfessionalTemplate: InvoiceTemplate = {
  id: SYSTEM_TEMPLATE_IDS.VERCEL_PROFESSIONAL,
  name: 'Vercel Professional',
  description: 'Structured professional design with branded header and organized sections',
  pageSize: 'A4',
  orientation: 'portrait',
  margins: {
    top: 50,
    right: 50,
    bottom: 50,
    left: 50,
  },
  theme: {
    primary: '#000000',
    secondary: '#171717',
    accent: '#0a0a0a',
    text: '#000000',
    textLight: '#666666',
    background: '#ffffff',
  },
  backgroundColor: '#ffffff',
  isDefault: false,
  isSystem: true,
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  elements: [
    // Black Header Bar - full width
    {
      id: 'sys-pro-header-bar',
      type: 'rectangle',
      name: 'Header Bar',
      position: { x: 0, y: 0, width: 495, height: 45 },
      content: '',
      backgroundColor: '#000000',
      padding: 0,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
    },
    // Company Name (in header)
    {
      id: 'sys-pro-company',
      type: 'text',
      name: 'Company Name',
      position: { x: 10, y: 12, width: 220, height: 22 },
      content: '{{from_name}}',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 14,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.2,
        color: '#ffffff',
      },
      padding: 0,
      opacity: 1,
      zIndex: 1,
      locked: false,
      visible: true,
    },
    // Invoice Badge (in header)
    {
      id: 'sys-pro-invoice-badge',
      type: 'text',
      name: 'Invoice Badge',
      position: { x: 405, y: 12, width: 80, height: 22 },
      content: 'INVOICE',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 12,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'right',
        textDecoration: 'none',
        textTransform: 'uppercase',
        letterSpacing: 2,
        lineHeight: 1.2,
        color: '#ffffff',
      },
      padding: 0,
      opacity: 1,
      zIndex: 2,
      locked: false,
      visible: true,
    },
    // Invoice Number & Date Row
    {
      id: 'sys-pro-invoice-meta',
      type: 'text',
      name: 'Invoice Meta',
      position: { x: 0, y: 58, width: 200, height: 32 },
      content: 'Invoice #{{invoice_number}}\nIssued: {{issue_date}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.6,
        color: '#000000',
      },
      padding: 0,
      opacity: 1,
      zIndex: 3,
      locked: false,
      visible: true,
    },
    // Due Date (right)
    {
      id: 'sys-pro-due-date',
      type: 'text',
      name: 'Due Date',
      position: { x: 315, y: 58, width: 180, height: 32 },
      content: 'Due: {{due_date}}\nPeriod: {{billing_period}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'right',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.6,
        color: '#000000',
      },
      padding: 0,
      opacity: 1,
      zIndex: 4,
      locked: false,
      visible: true,
    },
    // Divider - full width
    {
      id: 'sys-pro-divider-1',
      type: 'divider',
      name: 'Section Divider',
      position: { x: 0, y: 98, width: 495, height: 1 },
      content: '',
      backgroundColor: '#e5e5e5',
      padding: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
    },
    // From Section Box - width=210
    {
      id: 'sys-pro-from-box',
      type: 'rectangle',
      name: 'From Box',
      position: { x: 0, y: 110, width: 210, height: 70 },
      content: '',
      backgroundColor: '#fafafa',
      border: {
        width: 1,
        color: '#e5e5e5',
        style: 'solid',
        radius: 4,
      },
      padding: 0,
      opacity: 1,
      zIndex: 6,
      locked: false,
      visible: true,
    },
    // From Label
    {
      id: 'sys-pro-from-label',
      type: 'text',
      name: 'From Label',
      position: { x: 8, y: 116, width: 50, height: 10 },
      content: 'FROM',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 7,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'uppercase',
        letterSpacing: 1,
        lineHeight: 1.2,
        color: '#999999',
      },
      padding: 0,
      opacity: 1,
      zIndex: 7,
      locked: false,
      visible: true,
    },
    // From Details
    {
      id: 'sys-pro-from-details',
      type: 'text',
      name: 'From Details',
      position: { x: 8, y: 128, width: 194, height: 48 },
      content: '{{from_address}}\n{{from_city}}, {{from_state}} {{from_postal_code}}\n{{from_email}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.4,
        color: '#333333',
      },
      padding: 0,
      opacity: 1,
      zIndex: 8,
      locked: false,
      visible: true,
    },
    // Bill To Section Box
    {
      id: 'sys-pro-to-box',
      type: 'rectangle',
      name: 'Bill To Box',
      position: { x: 285, y: 110, width: 210, height: 70 },
      content: '',
      backgroundColor: '#fafafa',
      border: {
        width: 1,
        color: '#e5e5e5',
        style: 'solid',
        radius: 4,
      },
      padding: 0,
      opacity: 1,
      zIndex: 9,
      locked: false,
      visible: true,
    },
    // Bill To Label
    {
      id: 'sys-pro-to-label',
      type: 'text',
      name: 'Bill To Label',
      position: { x: 293, y: 116, width: 50, height: 10 },
      content: 'BILL TO',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 7,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'uppercase',
        letterSpacing: 1,
        lineHeight: 1.2,
        color: '#999999',
      },
      padding: 0,
      opacity: 1,
      zIndex: 10,
      locked: false,
      visible: true,
    },
    // Bill To Details
    {
      id: 'sys-pro-to-details',
      type: 'text',
      name: 'Bill To Details',
      position: { x: 293, y: 128, width: 194, height: 48 },
      content: '{{to_name}}\n{{to_address}}\n{{to_city}}, {{to_state}} {{to_postal_code}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.4,
        color: '#333333',
      },
      padding: 0,
      opacity: 1,
      zIndex: 11,
      locked: false,
      visible: true,
    },
    // Work Hours Table - full width
    {
      id: 'sys-pro-work-hours',
      type: 'table_work_hours',
      name: 'Work Hours',
      position: { x: 0, y: 195, width: 495, height: 130 },
      content: '',
      tableStyle: {
        headerBackgroundColor: '#000000',
        headerTextColor: '#ffffff',
        rowBackgroundColor: '#ffffff',
        alternateRowBackgroundColor: '#fafafa',
        borderColor: '#e5e5e5',
        showHeaderBorder: true,
        showRowBorders: true,
      },
      padding: 0,
      opacity: 1,
      zIndex: 12,
      locked: false,
      visible: true,
    },
    // Line Items Table - full width
    {
      id: 'sys-pro-line-items',
      type: 'table_line_items',
      name: 'Line Items',
      position: { x: 0, y: 335, width: 495, height: 85 },
      content: '',
      tableStyle: {
        headerBackgroundColor: '#000000',
        headerTextColor: '#ffffff',
        rowBackgroundColor: '#ffffff',
        alternateRowBackgroundColor: '#fafafa',
        borderColor: '#e5e5e5',
        showHeaderBorder: true,
        showRowBorders: true,
      },
      padding: 0,
      opacity: 1,
      zIndex: 13,
      locked: false,
      visible: true,
    },
    // Summary Box
    {
      id: 'sys-pro-summary-box',
      type: 'rectangle',
      name: 'Summary Box',
      position: { x: 310, y: 435, width: 185, height: 90 },
      content: '',
      backgroundColor: '#fafafa',
      border: {
        width: 1,
        color: '#e5e5e5',
        style: 'solid',
        radius: 4,
      },
      padding: 0,
      opacity: 1,
      zIndex: 14,
      locked: false,
      visible: true,
    },
    // Summary Table
    {
      id: 'sys-pro-summary',
      type: 'table_summary',
      name: 'Summary',
      position: { x: 318, y: 442, width: 169, height: 78 },
      content: '',
      tableStyle: {
        headerBackgroundColor: '#000000',
        headerTextColor: '#ffffff',
        rowBackgroundColor: 'transparent',
        alternateRowBackgroundColor: 'transparent',
        borderColor: '#e5e5e5',
        showHeaderBorder: false,
        showRowBorders: false,
      },
      padding: 0,
      opacity: 1,
      zIndex: 15,
      locked: false,
      visible: true,
    },
    // Notes Section
    {
      id: 'sys-pro-notes-label',
      type: 'text',
      name: 'Notes Label',
      position: { x: 0, y: 435, width: 50, height: 10 },
      content: 'NOTES',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 7,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'uppercase',
        letterSpacing: 1,
        lineHeight: 1.2,
        color: '#999999',
      },
      padding: 0,
      opacity: 1,
      zIndex: 16,
      locked: false,
      visible: true,
    },
    {
      id: 'sys-pro-notes',
      type: 'text',
      name: 'Notes',
      position: { x: 0, y: 448, width: 230, height: 45 },
      content: '{{notes}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.4,
        color: '#666666',
      },
      padding: 0,
      opacity: 1,
      zIndex: 17,
      locked: false,
      visible: true,
    },
    // Footer - full width, centered
    {
      id: 'sys-pro-footer',
      type: 'text',
      name: 'Footer',
      position: { x: 0, y: 540, width: 495, height: 16 },
      content: 'Thank you for your business.',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.2,
        color: '#999999',
      },
      padding: 0,
      opacity: 1,
      zIndex: 18,
      locked: false,
      visible: true,
    },
  ],
}

/**
 * Template 3: Vercel Executive
 *
 * - Premium, executive-level design
 * - Dark charcoal accent (#171717)
 * - Elegant typography with refined spacing
 * - Subtle gradient-like visual hierarchy
 */
const vercelExecutiveTemplate: InvoiceTemplate = {
  id: SYSTEM_TEMPLATE_IDS.VERCEL_EXECUTIVE,
  name: 'Vercel Executive',
  description: 'Premium executive design with refined typography and elegant visual hierarchy',
  pageSize: 'A4',
  orientation: 'portrait',
  margins: {
    top: 50,
    right: 50,
    bottom: 50,
    left: 50,
  },
  theme: {
    primary: '#171717',
    secondary: '#404040',
    accent: '#737373',
    text: '#171717',
    textLight: '#737373',
    background: '#ffffff',
  },
  backgroundColor: '#ffffff',
  isDefault: false,
  isSystem: true,
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  elements: [
    // Left vertical accent line
    {
      id: 'sys-exec-accent-line',
      type: 'rectangle',
      name: 'Accent Line',
      position: { x: 0, y: 0, width: 3, height: 80 },
      content: '',
      backgroundColor: '#171717',
      padding: 0,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
    },
    // INVOICE Title (elegant, spaced)
    {
      id: 'sys-exec-title',
      type: 'text',
      name: 'Invoice Title',
      position: { x: 16, y: 8, width: 200, height: 36 },
      content: 'INVOICE',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 28,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'uppercase',
        letterSpacing: 8,
        lineHeight: 1.2,
        color: '#171717',
      },
      padding: 0,
      opacity: 1,
      zIndex: 1,
      locked: false,
      visible: true,
    },
    // Invoice Number (subtle)
    {
      id: 'sys-exec-invoice-number',
      type: 'text',
      name: 'Invoice Number',
      position: { x: 16, y: 48, width: 180, height: 20 },
      content: 'No. {{invoice_number}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 10,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 1,
        lineHeight: 1.4,
        color: '#737373',
      },
      padding: 0,
      opacity: 1,
      zIndex: 2,
      locked: false,
      visible: true,
    },
    // Company Name (right aligned)
    {
      id: 'sys-exec-company',
      type: 'text',
      name: 'Company',
      position: { x: 295, y: 8, width: 200, height: 24 },
      content: '{{from_name}}',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 12,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'right',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.4,
        color: '#171717',
      },
      padding: 0,
      opacity: 1,
      zIndex: 3,
      locked: false,
      visible: true,
    },
    // Company Address (right aligned)
    {
      id: 'sys-exec-company-address',
      type: 'text',
      name: 'Company Address',
      position: { x: 295, y: 32, width: 200, height: 48 },
      content: '{{from_address}}\n{{from_city}}, {{from_state}} {{from_postal_code}}\n{{from_email}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'right',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.5,
        color: '#525252',
      },
      padding: 0,
      opacity: 1,
      zIndex: 4,
      locked: false,
      visible: true,
    },
    // Horizontal divider
    {
      id: 'sys-exec-divider-1',
      type: 'divider',
      name: 'Divider',
      position: { x: 0, y: 90, width: 495, height: 1 },
      content: '',
      backgroundColor: '#e5e5e5',
      padding: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
    },
    // Billed To Section
    {
      id: 'sys-exec-billed-label',
      type: 'text',
      name: 'Billed To Label',
      position: { x: 0, y: 105, width: 80, height: 14 },
      content: 'BILLED TO',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'uppercase',
        letterSpacing: 2,
        lineHeight: 1.2,
        color: '#a3a3a3',
      },
      padding: 0,
      opacity: 1,
      zIndex: 6,
      locked: false,
      visible: true,
    },
    {
      id: 'sys-exec-billed-to',
      type: 'text',
      name: 'Billed To',
      position: { x: 0, y: 122, width: 200, height: 55 },
      content: '{{to_name}}\n{{to_address}}\n{{to_city}}, {{to_state}} {{to_postal_code}}\n{{to_email}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.5,
        color: '#404040',
      },
      padding: 0,
      opacity: 1,
      zIndex: 7,
      locked: false,
      visible: true,
    },
    // Invoice Details (right)
    {
      id: 'sys-exec-details-label',
      type: 'text',
      name: 'Details Label',
      position: { x: 375, y: 105, width: 120, height: 14 },
      content: 'INVOICE DETAILS',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'right',
        textDecoration: 'none',
        textTransform: 'uppercase',
        letterSpacing: 2,
        lineHeight: 1.2,
        color: '#a3a3a3',
      },
      padding: 0,
      opacity: 1,
      zIndex: 8,
      locked: false,
      visible: true,
    },
    {
      id: 'sys-exec-details',
      type: 'text',
      name: 'Details',
      position: { x: 335, y: 122, width: 160, height: 55 },
      content: 'Issue Date: {{issue_date}}\nDue Date: {{due_date}}\nPeriod: {{billing_period}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'right',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.8,
        color: '#404040',
      },
      padding: 0,
      opacity: 1,
      zIndex: 9,
      locked: false,
      visible: true,
    },
    // Work Hours Table
    {
      id: 'sys-exec-work-hours',
      type: 'table_work_hours',
      name: 'Work Hours',
      position: { x: 0, y: 190, width: 495, height: 130 },
      content: '',
      tableStyle: {
        headerBackgroundColor: '#171717',
        headerTextColor: '#ffffff',
        rowBackgroundColor: '#ffffff',
        alternateRowBackgroundColor: '#fafafa',
        borderColor: '#e5e5e5',
        showHeaderBorder: true,
        showRowBorders: true,
      },
      padding: 0,
      opacity: 1,
      zIndex: 10,
      locked: false,
      visible: true,
    },
    // Line Items Table
    {
      id: 'sys-exec-line-items',
      type: 'table_line_items',
      name: 'Line Items',
      position: { x: 0, y: 330, width: 495, height: 85 },
      content: '',
      tableStyle: {
        headerBackgroundColor: '#171717',
        headerTextColor: '#ffffff',
        rowBackgroundColor: '#ffffff',
        alternateRowBackgroundColor: '#fafafa',
        borderColor: '#e5e5e5',
        showHeaderBorder: true,
        showRowBorders: true,
      },
      padding: 0,
      opacity: 1,
      zIndex: 11,
      locked: false,
      visible: true,
    },
    // Summary Table
    {
      id: 'sys-exec-summary',
      type: 'table_summary',
      name: 'Summary',
      position: { x: 305, y: 430, width: 190, height: 85 },
      content: '',
      tableStyle: {
        headerBackgroundColor: '#171717',
        headerTextColor: '#ffffff',
        rowBackgroundColor: '#ffffff',
        alternateRowBackgroundColor: '#fafafa',
        borderColor: '#e5e5e5',
        showHeaderBorder: false,
        showRowBorders: true,
      },
      padding: 0,
      opacity: 1,
      zIndex: 12,
      locked: false,
      visible: true,
    },
    // Notes
    {
      id: 'sys-exec-notes-label',
      type: 'text',
      name: 'Notes Label',
      position: { x: 0, y: 430, width: 60, height: 14 },
      content: 'NOTES',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'uppercase',
        letterSpacing: 2,
        lineHeight: 1.2,
        color: '#a3a3a3',
      },
      padding: 0,
      opacity: 1,
      zIndex: 13,
      locked: false,
      visible: true,
    },
    {
      id: 'sys-exec-notes',
      type: 'text',
      name: 'Notes',
      position: { x: 0, y: 448, width: 220, height: 50 },
      content: '{{notes}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.5,
        color: '#737373',
      },
      padding: 0,
      opacity: 1,
      zIndex: 14,
      locked: false,
      visible: true,
    },
    // Footer accent line
    {
      id: 'sys-exec-footer-line',
      type: 'divider',
      name: 'Footer Line',
      position: { x: 0, y: 530, width: 495, height: 1 },
      content: '',
      backgroundColor: '#171717',
      padding: 0,
      opacity: 1,
      zIndex: 15,
      locked: false,
      visible: true,
    },
    // Footer
    {
      id: 'sys-exec-footer',
      type: 'text',
      name: 'Footer',
      position: { x: 0, y: 540, width: 495, height: 16 },
      content: 'Thank you for your business',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 1,
        lineHeight: 1.2,
        color: '#a3a3a3',
      },
      padding: 0,
      opacity: 1,
      zIndex: 16,
      locked: false,
      visible: true,
    },
  ],
}

/**
 * Template 4: Vercel Modern
 *
 * - Contemporary asymmetric design
 * - Bold typography contrasts
 * - Floating card-style sections
 * - Clean visual rhythm
 */
const vercelModernTemplate: InvoiceTemplate = {
  id: SYSTEM_TEMPLATE_IDS.VERCEL_MODERN,
  name: 'Vercel Modern',
  description: 'Contemporary design with bold typography and floating card sections',
  pageSize: 'A4',
  orientation: 'portrait',
  margins: {
    top: 50,
    right: 50,
    bottom: 50,
    left: 50,
  },
  theme: {
    primary: '#000000',
    secondary: '#262626',
    accent: '#525252',
    text: '#000000',
    textLight: '#71717a',
    background: '#fafafa',
  },
  backgroundColor: '#fafafa',
  isDefault: false,
  isSystem: true,
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  elements: [
    // Background white card
    {
      id: 'sys-mod-bg-card',
      type: 'rectangle',
      name: 'Background Card',
      position: { x: 0, y: 0, width: 495, height: 560 },
      content: '',
      backgroundColor: '#ffffff',
      border: {
        width: 1,
        color: '#e4e4e7',
        style: 'solid',
        radius: 8,
      },
      padding: 0,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
    },
    // Large Invoice Number (hero element)
    {
      id: 'sys-mod-invoice-number',
      type: 'text',
      name: 'Invoice Number',
      position: { x: 20, y: 20, width: 250, height: 42 },
      content: '#{{invoice_number}}',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 32,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.1,
        color: '#000000',
      },
      padding: 0,
      opacity: 1,
      zIndex: 1,
      locked: false,
      visible: true,
    },
    // Invoice label (small)
    {
      id: 'sys-mod-invoice-label',
      type: 'text',
      name: 'Invoice Label',
      position: { x: 20, y: 62, width: 80, height: 14 },
      content: 'INVOICE',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'uppercase',
        letterSpacing: 3,
        lineHeight: 1.2,
        color: '#71717a',
      },
      padding: 0,
      opacity: 1,
      zIndex: 2,
      locked: false,
      visible: true,
    },
    // From name (right)
    {
      id: 'sys-mod-from-name',
      type: 'text',
      name: 'From Name',
      position: { x: 315, y: 20, width: 160, height: 20 },
      content: '{{from_name}}',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 11,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'right',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.4,
        color: '#000000',
      },
      padding: 0,
      opacity: 1,
      zIndex: 3,
      locked: false,
      visible: true,
    },
    // From address
    {
      id: 'sys-mod-from-address',
      type: 'text',
      name: 'From Address',
      position: { x: 315, y: 40, width: 160, height: 45 },
      content: '{{from_address}}\n{{from_city}}, {{from_state}}\n{{from_email}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'right',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.5,
        color: '#71717a',
      },
      padding: 0,
      opacity: 1,
      zIndex: 4,
      locked: false,
      visible: true,
    },
    // Dates row (inline style)
    {
      id: 'sys-mod-dates',
      type: 'text',
      name: 'Dates',
      position: { x: 20, y: 90, width: 400, height: 16 },
      content: 'Issued {{issue_date}}  •  Due {{due_date}}  •  Period: {{billing_period}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.4,
        color: '#52525b',
      },
      padding: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
    },
    // Bill To card
    {
      id: 'sys-mod-bill-to-card',
      type: 'rectangle',
      name: 'Bill To Card',
      position: { x: 20, y: 120, width: 200, height: 65 },
      content: '',
      backgroundColor: '#f4f4f5',
      border: {
        width: 0,
        color: 'transparent',
        style: 'solid',
        radius: 6,
      },
      padding: 0,
      opacity: 1,
      zIndex: 6,
      locked: false,
      visible: true,
    },
    // Bill To label
    {
      id: 'sys-mod-bill-to-label',
      type: 'text',
      name: 'Bill To Label',
      position: { x: 30, y: 128, width: 60, height: 12 },
      content: 'BILL TO',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 7,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'uppercase',
        letterSpacing: 2,
        lineHeight: 1.2,
        color: '#a1a1aa',
      },
      padding: 0,
      opacity: 1,
      zIndex: 7,
      locked: false,
      visible: true,
    },
    // Bill To details
    {
      id: 'sys-mod-bill-to',
      type: 'text',
      name: 'Bill To',
      position: { x: 30, y: 142, width: 180, height: 38 },
      content: '{{to_name}}\n{{to_address}}, {{to_city}}\n{{to_email}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.4,
        color: '#27272a',
      },
      padding: 0,
      opacity: 1,
      zIndex: 8,
      locked: false,
      visible: true,
    },
    // Work Hours Table
    {
      id: 'sys-mod-work-hours',
      type: 'table_work_hours',
      name: 'Work Hours',
      position: { x: 20, y: 200, width: 400, height: 120 },
      content: '',
      tableStyle: {
        headerBackgroundColor: '#18181b',
        headerTextColor: '#ffffff',
        rowBackgroundColor: '#ffffff',
        alternateRowBackgroundColor: '#f4f4f5',
        borderColor: '#e4e4e7',
        showHeaderBorder: true,
        showRowBorders: false,
      },
      padding: 0,
      opacity: 1,
      zIndex: 9,
      locked: false,
      visible: true,
    },
    // Line Items Table
    {
      id: 'sys-mod-line-items',
      type: 'table_line_items',
      name: 'Line Items',
      position: { x: 20, y: 330, width: 400, height: 80 },
      content: '',
      tableStyle: {
        headerBackgroundColor: '#18181b',
        headerTextColor: '#ffffff',
        rowBackgroundColor: '#ffffff',
        alternateRowBackgroundColor: '#f4f4f5',
        borderColor: '#e4e4e7',
        showHeaderBorder: true,
        showRowBorders: false,
      },
      padding: 0,
      opacity: 1,
      zIndex: 10,
      locked: false,
      visible: true,
    },
    // Summary Table
    {
      id: 'sys-mod-summary',
      type: 'table_summary',
      name: 'Summary',
      position: { x: 295, y: 425, width: 180, height: 80 },
      content: '',
      tableStyle: {
        headerBackgroundColor: '#000000',
        headerTextColor: '#ffffff',
        rowBackgroundColor: '#f4f4f5',
        alternateRowBackgroundColor: '#ffffff',
        borderColor: 'transparent',
        showHeaderBorder: false,
        showRowBorders: false,
      },
      padding: 0,
      opacity: 1,
      zIndex: 11,
      locked: false,
      visible: true,
    },
    // Notes
    {
      id: 'sys-mod-notes-label',
      type: 'text',
      name: 'Notes Label',
      position: { x: 20, y: 425, width: 50, height: 12 },
      content: 'Notes',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.2,
        color: '#a1a1aa',
      },
      padding: 0,
      opacity: 1,
      zIndex: 12,
      locked: false,
      visible: true,
    },
    {
      id: 'sys-mod-notes',
      type: 'text',
      name: 'Notes',
      position: { x: 20, y: 440, width: 200, height: 50 },
      content: '{{notes}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.4,
        color: '#52525b',
      },
      padding: 0,
      opacity: 1,
      zIndex: 13,
      locked: false,
      visible: true,
    },
    // Footer
    {
      id: 'sys-mod-footer',
      type: 'text',
      name: 'Footer',
      position: { x: 20, y: 525, width: 400, height: 16 },
      content: 'Thank you for your business.',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.2,
        color: '#a1a1aa',
      },
      padding: 0,
      opacity: 1,
      zIndex: 14,
      locked: false,
      visible: true,
    },
  ],
}

/**
 * Template 5: Vercel Classic
 *
 * - Timeless professional design
 * - Traditional layout with modern touches
 * - Clear visual hierarchy
 * - Balanced whitespace
 */
const vercelClassicTemplate: InvoiceTemplate = {
  id: SYSTEM_TEMPLATE_IDS.VERCEL_CLASSIC,
  name: 'Vercel Classic',
  description: 'Timeless professional design with traditional layout and modern touches',
  pageSize: 'A4',
  orientation: 'portrait',
  margins: {
    top: 50,
    right: 50,
    bottom: 50,
    left: 50,
  },
  theme: {
    primary: '#111827',
    secondary: '#374151',
    accent: '#6b7280',
    text: '#111827',
    textLight: '#6b7280',
    background: '#ffffff',
  },
  backgroundColor: '#ffffff',
  isDefault: false,
  isSystem: true,
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  elements: [
    // Company name (top left, large)
    {
      id: 'sys-classic-company',
      type: 'text',
      name: 'Company Name',
      position: { x: 0, y: 0, width: 220, height: 26 },
      content: '{{from_name}}',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 18,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.2,
        color: '#111827',
      },
      padding: 0,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
    },
    // Company address
    {
      id: 'sys-classic-company-addr',
      type: 'text',
      name: 'Company Address',
      position: { x: 0, y: 28, width: 220, height: 45 },
      content: '{{from_address}}\n{{from_city}}, {{from_state}} {{from_postal_code}}\n{{from_email}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.5,
        color: '#6b7280',
      },
      padding: 0,
      opacity: 1,
      zIndex: 1,
      locked: false,
      visible: true,
    },
    // INVOICE badge (top right)
    {
      id: 'sys-classic-badge',
      type: 'rectangle',
      name: 'Invoice Badge',
      position: { x: 395, y: 0, width: 100, height: 28 },
      content: '',
      backgroundColor: '#111827',
      border: {
        width: 0,
        color: 'transparent',
        style: 'solid',
        radius: 4,
      },
      padding: 0,
      opacity: 1,
      zIndex: 2,
      locked: false,
      visible: true,
    },
    {
      id: 'sys-classic-badge-text',
      type: 'text',
      name: 'Invoice Badge Text',
      position: { x: 395, y: 6, width: 100, height: 18 },
      content: 'INVOICE',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 11,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'center',
        textDecoration: 'none',
        textTransform: 'uppercase',
        letterSpacing: 2,
        lineHeight: 1.2,
        color: '#ffffff',
      },
      padding: 0,
      opacity: 1,
      zIndex: 3,
      locked: false,
      visible: true,
    },
    // Invoice number
    {
      id: 'sys-classic-number',
      type: 'text',
      name: 'Invoice Number',
      position: { x: 355, y: 36, width: 140, height: 16 },
      content: '#{{invoice_number}}',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 11,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'right',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.4,
        color: '#111827',
      },
      padding: 0,
      opacity: 1,
      zIndex: 4,
      locked: false,
      visible: true,
    },
    // Dates
    {
      id: 'sys-classic-dates',
      type: 'text',
      name: 'Dates',
      position: { x: 355, y: 54, width: 140, height: 35 },
      content: 'Date: {{issue_date}}\nDue: {{due_date}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'right',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.6,
        color: '#6b7280',
      },
      padding: 0,
      opacity: 1,
      zIndex: 5,
      locked: false,
      visible: true,
    },
    // Divider
    {
      id: 'sys-classic-divider-1',
      type: 'divider',
      name: 'Section Divider',
      position: { x: 0, y: 85, width: 495, height: 2 },
      content: '',
      backgroundColor: '#111827',
      padding: 0,
      opacity: 1,
      zIndex: 6,
      locked: false,
      visible: true,
    },
    // Bill To
    {
      id: 'sys-classic-bill-to-label',
      type: 'text',
      name: 'Bill To Label',
      position: { x: 0, y: 100, width: 60, height: 14 },
      content: 'Bill To',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 9,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.2,
        color: '#111827',
      },
      padding: 0,
      opacity: 1,
      zIndex: 7,
      locked: false,
      visible: true,
    },
    {
      id: 'sys-classic-bill-to',
      type: 'text',
      name: 'Bill To',
      position: { x: 0, y: 116, width: 200, height: 55 },
      content: '{{to_name}}\n{{to_address}}\n{{to_city}}, {{to_state}} {{to_postal_code}}\n{{to_email}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.5,
        color: '#374151',
      },
      padding: 0,
      opacity: 1,
      zIndex: 8,
      locked: false,
      visible: true,
    },
    // Period
    {
      id: 'sys-classic-period-label',
      type: 'text',
      name: 'Period Label',
      position: { x: 355, y: 100, width: 140, height: 14 },
      content: 'Billing Period',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 9,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'right',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.2,
        color: '#111827',
      },
      padding: 0,
      opacity: 1,
      zIndex: 9,
      locked: false,
      visible: true,
    },
    {
      id: 'sys-classic-period',
      type: 'text',
      name: 'Period',
      position: { x: 355, y: 116, width: 140, height: 16 },
      content: '{{billing_period}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'right',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.4,
        color: '#374151',
      },
      padding: 0,
      opacity: 1,
      zIndex: 10,
      locked: false,
      visible: true,
    },
    // Work Hours Table
    {
      id: 'sys-classic-work-hours',
      type: 'table_work_hours',
      name: 'Work Hours',
      position: { x: 0, y: 180, width: 495, height: 130 },
      content: '',
      tableStyle: {
        headerBackgroundColor: '#f3f4f6',
        headerTextColor: '#111827',
        rowBackgroundColor: '#ffffff',
        alternateRowBackgroundColor: '#f9fafb',
        borderColor: '#e5e7eb',
        showHeaderBorder: true,
        showRowBorders: true,
      },
      padding: 0,
      opacity: 1,
      zIndex: 11,
      locked: false,
      visible: true,
    },
    // Line Items Table
    {
      id: 'sys-classic-line-items',
      type: 'table_line_items',
      name: 'Line Items',
      position: { x: 0, y: 320, width: 495, height: 85 },
      content: '',
      tableStyle: {
        headerBackgroundColor: '#f3f4f6',
        headerTextColor: '#111827',
        rowBackgroundColor: '#ffffff',
        alternateRowBackgroundColor: '#f9fafb',
        borderColor: '#e5e7eb',
        showHeaderBorder: true,
        showRowBorders: true,
      },
      padding: 0,
      opacity: 1,
      zIndex: 12,
      locked: false,
      visible: true,
    },
    // Summary box
    {
      id: 'sys-classic-summary-box',
      type: 'rectangle',
      name: 'Summary Box',
      position: { x: 310, y: 420, width: 185, height: 90 },
      content: '',
      backgroundColor: '#f9fafb',
      border: {
        width: 1,
        color: '#e5e7eb',
        style: 'solid',
        radius: 4,
      },
      padding: 0,
      opacity: 1,
      zIndex: 13,
      locked: false,
      visible: true,
    },
    // Summary Table
    {
      id: 'sys-classic-summary',
      type: 'table_summary',
      name: 'Summary',
      position: { x: 318, y: 428, width: 169, height: 78 },
      content: '',
      tableStyle: {
        headerBackgroundColor: '#111827',
        headerTextColor: '#ffffff',
        rowBackgroundColor: 'transparent',
        alternateRowBackgroundColor: 'transparent',
        borderColor: 'transparent',
        showHeaderBorder: false,
        showRowBorders: false,
      },
      padding: 0,
      opacity: 1,
      zIndex: 14,
      locked: false,
      visible: true,
    },
    // Notes
    {
      id: 'sys-classic-notes-label',
      type: 'text',
      name: 'Notes Label',
      position: { x: 0, y: 420, width: 50, height: 14 },
      content: 'Notes',
      fontStyle: {
        fontFamily: 'Helvetica-Bold',
        fontSize: 9,
        fontWeight: 'bold',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.2,
        color: '#111827',
      },
      padding: 0,
      opacity: 1,
      zIndex: 15,
      locked: false,
      visible: true,
    },
    {
      id: 'sys-classic-notes',
      type: 'text',
      name: 'Notes',
      position: { x: 0, y: 436, width: 230, height: 50 },
      content: '{{notes}}',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 9,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'left',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.4,
        color: '#6b7280',
      },
      padding: 0,
      opacity: 1,
      zIndex: 16,
      locked: false,
      visible: true,
    },
    // Footer divider
    {
      id: 'sys-classic-footer-divider',
      type: 'divider',
      name: 'Footer Divider',
      position: { x: 0, y: 525, width: 495, height: 1 },
      content: '',
      backgroundColor: '#e5e7eb',
      padding: 0,
      opacity: 1,
      zIndex: 17,
      locked: false,
      visible: true,
    },
    // Footer
    {
      id: 'sys-classic-footer',
      type: 'text',
      name: 'Footer',
      position: { x: 0, y: 535, width: 495, height: 16 },
      content: 'Thank you for your business. Payment is due within the specified terms.',
      fontStyle: {
        fontFamily: 'Helvetica',
        fontSize: 8,
        fontWeight: 'normal',
        fontStyle: 'normal',
        textAlign: 'center',
        textDecoration: 'none',
        textTransform: 'none',
        letterSpacing: 0,
        lineHeight: 1.2,
        color: '#9ca3af',
      },
      padding: 0,
      opacity: 1,
      zIndex: 18,
      locked: false,
      visible: true,
    },
  ],
}

/**
 * All system templates
 * These are merged with user templates at runtime
 */
export const SYSTEM_TEMPLATES: InvoiceTemplate[] = [
  vercelMinimalTemplate,
  vercelProfessionalTemplate,
  vercelExecutiveTemplate,
  vercelModernTemplate,
  vercelClassicTemplate,
]

/**
 * Check if a template ID is a system template
 */
export function isSystemTemplate(templateId: string): boolean {
  return Object.values(SYSTEM_TEMPLATE_IDS).includes(templateId as typeof SYSTEM_TEMPLATE_IDS[keyof typeof SYSTEM_TEMPLATE_IDS])
}

/**
 * Get a system template by ID
 */
export function getSystemTemplate(templateId: string): InvoiceTemplate | undefined {
  return SYSTEM_TEMPLATES.find((t) => t.id === templateId)
}
