import type { PredefinedElement, TemplateElement } from '@invoice-generator/shared-types'

// Default font style for text elements
const defaultFontStyle: TemplateElement['fontStyle'] = {
  fontFamily: 'Helvetica',
  fontSize: 12,
  fontWeight: 'normal',
  fontStyle: 'normal',
  textAlign: 'left',
  textDecoration: 'none',
  textTransform: 'none',
  letterSpacing: 0,
  lineHeight: 1.2,
  color: '#333333',
}

// Default positioning fields for all elements
const defaultPositioningFields = {
  positionMode: 'absolute' as const,
  order: 0,
  flexGrow: 0,
  flexShrink: 1,
  showWhenEmpty: false,
  minHeightMode: undefined, // 'none' by default - no minimum height constraint
}

// Default table style
const defaultTableStyle: TemplateElement['tableStyle'] = {
  headerBackgroundColor: '#1a1a2e',
  headerTextColor: '#ffffff',
  rowBackgroundColor: '#ffffff',
  alternateRowBackgroundColor: '#f8fafc',
  borderColor: '#e0e0e0',
  showHeaderBorder: true,
  showRowBorders: true,
}

export const PREDEFINED_ELEMENTS: PredefinedElement[] = [
  // Text Elements
  {
    id: 'invoice-title',
    category: 'text',
    name: 'Invoice Title',
    description: 'Large "INVOICE" heading',
    icon: 'Type',
    defaultElement: {
      type: 'text',
      name: 'Invoice Title',
      position: { x: 40, y: 40, width: 200, height: 40 },
      content: 'INVOICE',
      fontStyle: {
        ...defaultFontStyle,
        fontSize: 28,
        fontFamily: 'Helvetica-Bold',
        color: '#1a1a2e',
      },
      padding: 0,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
      ...defaultPositioningFields,
    },
  },
  {
    id: 'invoice-number',
    category: 'text',
    name: 'Invoice Number',
    description: 'Invoice # with token',
    icon: 'Hash',
    defaultElement: {
      type: 'text',
      name: 'Invoice Number',
      position: { x: 40, y: 85, width: 200, height: 25 },
      content: '#{{invoice_number}}',
      fontStyle: {
        ...defaultFontStyle,
        fontSize: 12,
        color: '#666666',
      },
      padding: 0,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
      ...defaultPositioningFields,
    },
  },
  {
    id: 'dates-block',
    category: 'text',
    name: 'Dates Block',
    description: 'Issue and due dates',
    icon: 'Calendar',
    defaultElement: {
      type: 'text',
      name: 'Dates Block',
      position: { x: 40, y: 120, width: 200, height: 50 },
      content: 'Issue Date: {{issue_date}}\nDue Date: {{due_date}}',
      fontStyle: {
        ...defaultFontStyle,
        fontSize: 10,
        lineHeight: 1.5,
      },
      padding: 8,
      backgroundColor: '#f8fafc',
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
      ...defaultPositioningFields,
    },
  },
  {
    id: 'total-amount',
    category: 'text',
    name: 'Total Amount',
    description: 'Large total display',
    icon: 'DollarSign',
    defaultElement: {
      type: 'text',
      name: 'Total Amount',
      position: { x: 400, y: 40, width: 155, height: 50 },
      content: '{{currency_symbol}}{{total_amount}}',
      fontStyle: {
        ...defaultFontStyle,
        fontSize: 24,
        fontFamily: 'Helvetica-Bold',
        textAlign: 'right',
        color: '#1a1a2e',
      },
      padding: 10,
      backgroundColor: '#f0f9ff',
      border: {
        width: 0,
        color: '#0f3460',
        style: 'solid',
        radius: 4,
      },
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
      ...defaultPositioningFields,
    },
  },
  {
    id: 'custom-text',
    category: 'text',
    name: 'Custom Text',
    description: 'Editable text block',
    icon: 'TextCursor',
    defaultElement: {
      type: 'text',
      name: 'Custom Text',
      position: { x: 40, y: 200, width: 200, height: 30 },
      content: 'Enter your text here',
      fontStyle: defaultFontStyle,
      padding: 4,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
      ...defaultPositioningFields,
    },
  },

  // Contact Blocks
  {
    id: 'from-block',
    category: 'contact',
    name: 'From Block',
    description: 'Sender information',
    icon: 'Building2',
    defaultElement: {
      type: 'text',
      name: 'From Block',
      position: { x: 350, y: 40, width: 205, height: 120 },
      content:
        '{{from_name}}\n{{from_address}}\n{{from_city}}, {{from_state}} {{from_postal_code}}\n{{from_country}}\n{{from_email}}\n{{from_phone}}',
      fontStyle: {
        ...defaultFontStyle,
        fontSize: 10,
        textAlign: 'right',
        lineHeight: 1.4,
      },
      padding: 0,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
      ...defaultPositioningFields,
    },
  },
  {
    id: 'to-block',
    category: 'contact',
    name: 'Bill To Block',
    description: 'Client information',
    icon: 'User',
    defaultElement: {
      type: 'text',
      name: 'Bill To Block',
      position: { x: 40, y: 180, width: 250, height: 130 },
      content:
        'Bill To:\n{{to_name}}\n{{to_address}}\n{{to_city}}, {{to_state}} {{to_postal_code}}\n{{to_country}}\n{{to_email}}',
      fontStyle: {
        ...defaultFontStyle,
        fontSize: 10,
        lineHeight: 1.4,
      },
      padding: 0,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
      ...defaultPositioningFields,
    },
  },
  {
    id: 'contact-details',
    category: 'contact',
    name: 'Contact Details',
    description: 'Email and phone',
    icon: 'Mail',
    defaultElement: {
      type: 'text',
      name: 'Contact Details',
      position: { x: 40, y: 320, width: 200, height: 40 },
      content: 'Email: {{from_email}}\nPhone: {{from_phone}}',
      fontStyle: {
        ...defaultFontStyle,
        fontSize: 9,
        lineHeight: 1.5,
      },
      padding: 0,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
      ...defaultPositioningFields,
    },
  },

  // Tables
  {
    id: 'work-hours-table',
    category: 'tables',
    name: 'Work Hours Table',
    description: 'Daily work hours breakdown',
    icon: 'Clock',
    defaultElement: {
      type: 'table_work_hours',
      name: 'Work Hours Table',
      position: { x: 40, y: 320, width: 515, height: 200 },
      content: '',
      tableStyle: {
        ...defaultTableStyle,
        columns: [
          { id: 'date', header: 'Date', field: 'date', width: 20, align: 'left' },
          { id: 'description', header: 'Description', field: 'description', width: 40, align: 'left' },
          { id: 'hours', header: 'Hours', field: 'hours', width: 15, align: 'right' },
          { id: 'rate', header: 'Rate', field: 'rate', width: 15, align: 'right' },
          { id: 'amount', header: 'Amount', field: 'amount', width: 15, align: 'right' },
        ],
      },
      padding: 0,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
      ...defaultPositioningFields,
    },
  },
  {
    id: 'line-items-table',
    category: 'tables',
    name: 'Line Items Table',
    description: 'Additional items and charges',
    icon: 'List',
    defaultElement: {
      type: 'table_line_items',
      name: 'Line Items Table',
      position: { x: 40, y: 380, width: 515, height: 150 },
      content: '',
      tableStyle: {
        ...defaultTableStyle,
        columns: [
          { id: 'item', header: 'Item', field: 'description', width: 50, align: 'left' },
          { id: 'qty', header: 'Qty', field: 'quantity', width: 15, align: 'right' },
          { id: 'price', header: 'Unit Price', field: 'unitPrice', width: 20, align: 'right' },
          { id: 'amount', header: 'Amount', field: 'amount', width: 15, align: 'right' },
        ],
      },
      padding: 0,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
      ...defaultPositioningFields,
    },
  },
  {
    id: 'summary-table',
    category: 'tables',
    name: 'Summary Table',
    description: 'Subtotal, discount, tax, total',
    icon: 'Calculator',
    defaultElement: {
      type: 'table_summary',
      name: 'Summary Table',
      position: { x: 350, y: 550, width: 205, height: 120 },
      content: '',
      tableStyle: {
        ...defaultTableStyle,
        headerBackgroundColor: 'transparent',
        headerTextColor: '#666666',
        showHeaderBorder: false,
      },
      padding: 0,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
      ...defaultPositioningFields,
    },
  },

  // Decorative
  {
    id: 'horizontal-divider',
    category: 'decorative',
    name: 'Horizontal Divider',
    description: 'Horizontal line separator',
    icon: 'Minus',
    defaultElement: {
      type: 'divider',
      name: 'Horizontal Divider',
      position: { x: 40, y: 160, width: 515, height: 2 },
      content: '',
      backgroundColor: '#e0e0e0',
      padding: 0,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
      ...defaultPositioningFields,
    },
  },
  {
    id: 'rectangle',
    category: 'decorative',
    name: 'Rectangle',
    description: 'Background shape',
    icon: 'Square',
    defaultElement: {
      type: 'rectangle',
      name: 'Rectangle',
      position: { x: 40, y: 200, width: 200, height: 100 },
      content: '',
      backgroundColor: '#f8fafc',
      border: {
        width: 1,
        color: '#e0e0e0',
        style: 'solid',
        radius: 4,
      },
      padding: 0,
      opacity: 1,
      zIndex: -1,
      locked: false,
      visible: true,
      ...defaultPositioningFields,
    },
  },
  {
    id: 'logo-placeholder',
    category: 'decorative',
    name: 'Logo',
    description: 'Company logo placeholder',
    icon: 'Image',
    defaultElement: {
      type: 'logo',
      name: 'Logo',
      position: { x: 40, y: 40, width: 120, height: 60 },
      content: '',
      logoUrl: '', // Will use from invoice data
      objectFit: 'contain',
      padding: 0,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
      ...defaultPositioningFields,
    },
  },

  // Layout Containers
  {
    id: 'layout-container-column',
    category: 'layout',
    name: 'Column Container',
    description: 'Stack elements vertically',
    icon: 'Rows3',
    defaultElement: {
      type: 'layout_container',
      name: 'Column Container',
      position: { x: 40, y: 200, width: 200, height: 200 },
      content: '',
      backgroundColor: 'rgba(59, 130, 246, 0.05)',
      border: {
        width: 1,
        color: '#3b82f6',
        style: 'dashed',
        radius: 4,
      },
      padding: 10,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
      positionMode: 'absolute',
      order: 0,
      flexGrow: 0,
      flexShrink: 1,
      showWhenEmpty: false,
      layoutConfig: {
        direction: 'column',
        gap: 8,
        align: 'stretch',
        justify: 'start',
        wrap: false,
      },
    },
  },
  {
    id: 'layout-container-row',
    category: 'layout',
    name: 'Row Container',
    description: 'Stack elements horizontally',
    icon: 'Columns3',
    defaultElement: {
      type: 'layout_container',
      name: 'Row Container',
      position: { x: 40, y: 200, width: 400, height: 100 },
      content: '',
      backgroundColor: 'rgba(16, 185, 129, 0.05)',
      border: {
        width: 1,
        color: '#10b981',
        style: 'dashed',
        radius: 4,
      },
      padding: 10,
      opacity: 1,
      zIndex: 0,
      locked: false,
      visible: true,
      positionMode: 'absolute',
      order: 0,
      flexGrow: 0,
      flexShrink: 1,
      showWhenEmpty: false,
      layoutConfig: {
        direction: 'row',
        gap: 8,
        align: 'stretch',
        justify: 'start',
        wrap: false,
      },
    },
  },
]

export const ELEMENT_CATEGORIES = [
  { id: 'text', name: 'Text Elements', icon: 'Type' },
  { id: 'contact', name: 'Contact Info', icon: 'Users' },
  { id: 'tables', name: 'Tables', icon: 'Table' },
  { id: 'decorative', name: 'Decorative', icon: 'Shapes' },
  { id: 'layout', name: 'Layout', icon: 'Layout' },
] as const
